name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven project
        run: mvn clean package

      - name: Download JavaFX jmods
        run: |
          curl -L -o javafx-jmods.zip https://download2.gluonhq.com/openjfx/21/openjfx-21_windows-x64_bin-jmods.zip
          tar -xf javafx-jmods.zip

      - name: Create runtime
        run: |
          jlink `
          --module-path "$env:JAVA_HOME\jmods;javafx-jmods-21/lib" `
          --add-modules java.base,java.desktop,javafx.controls,javafx.fxml `
          --output runtime

      - name: Create installer
        run: |
          jpackage `
          --name budget `
          --input target `
          --main-jar budget-1.0.0.jar `
          --main-class com.nolabke.Main `
          --runtime-image runtime `
          --type exe

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: budget-installer
          path: "*.exe"
