name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  APP_NAME: Budget
  MAIN_CLASS: com.nolabke.Main
  JAVA_VERSION: "25"
  JAVAFX_VERSION: "25.0.1"

jobs:

  build-windows:
    name: Windows installer
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Maven
        run: mvn clean package

      - name: Get application version
        shell: bash
        run: |
          echo "APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Download JavaFX jmods
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://download2.gluonhq.com/openjfx/${{ env.JAVAFX_VERSION }}/openjfx-${{ env.JAVAFX_VERSION }}_windows-x64_bin-jmods.zip" `
            -OutFile javafx.zip

          Expand-Archive javafx.zip -DestinationPath .

      - name: Create runtime
        shell: powershell
        run: |
          jlink `
          --module-path "$env:JAVA_HOME\jmods;javafx-jmods-${{ env.JAVAFX_VERSION }}" `
          --add-modules java.base,java.desktop,java.logging,java.net.http,java.xml,java.prefs,jdk.localedata,javafx.base,javafx.graphics,javafx.controls,javafx.fxml `
          --output runtime

          runtime\bin\java --version

      - name: Create EXE
        shell: powershell
        run: |
          jpackage `
          --name $env:APP_NAME `
          --app-version ${{ env.APP_VERSION }} `
          --input target `
          --main-jar budget-${{ env.APP_VERSION }}.jar `
          --main-class $env:MAIN_CLASS `
          --runtime-image runtime `
          --java-options "--enable-native-access=javafx.graphics" `
          --type exe `
          --win-menu `
          --win-shortcut `
          --win-console

      - name: Rename Windows installer
        shell: powershell
        run: |
          Rename-Item `
            Budget-${{ env.APP_VERSION }}.exe `
            budget_${{ env.APP_VERSION }}_amd64.exe

      - name: Upload Windows
        uses: actions/upload-artifact@v5
        with:
          name: windows-installer
          path: "*.exe"



  build-linux:
    name: Linux installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Maven
        run: mvn clean package

      - name: Get application version
        shell: bash
        run: |
          echo "APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Download JavaFX jmods
        run: |
          wget https://download2.gluonhq.com/openjfx/${{ env.JAVAFX_VERSION }}/openjfx-${{ env.JAVAFX_VERSION }}_linux-x64_bin-jmods.zip
          unzip openjfx-${{ env.JAVAFX_VERSION }}_linux-x64_bin-jmods.zip

      - name: Create runtime
        run: |
          jlink \
          --module-path "$JAVA_HOME/jmods:javafx-jmods-${{ env.JAVAFX_VERSION }}" \
          --add-modules java.base,java.desktop,java.logging,java.net.http,java.xml,java.prefs,jdk.localedata,javafx.base,javafx.graphics,javafx.controls,javafx.fxml \
          --output runtime

      - name: Create DEB
        run: |
          jpackage \
          --name ${{ env.APP_NAME }} \
          --app-version ${{ env.APP_VERSION }} \
          --input target \
          --main-jar budget-${{ env.APP_VERSION }}.jar \
          --main-class ${{ env.MAIN_CLASS }} \
          --runtime-image runtime \
          --java-options "--enable-native-access=javafx.graphics" \
          --type deb

      - name: Rename Linux installer
        run: |
          mv \
          budget_${APP_VERSION}_amd64.deb \
          budget_${APP_VERSION}_amd64.deb

      - name: Upload Linux
        uses: actions/upload-artifact@v5
        with:
          name: linux-installer
          path: "*.deb"



  build-macos:
    name: macOS installer
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Maven
        run: mvn clean package

      - name: Get application version
        shell: bash
        run: |
          echo "APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Download JavaFX jmods
        run: |
          curl -L \
          -o javafx.zip \
          https://download2.gluonhq.com/openjfx/${{ env.JAVAFX_VERSION }}/openjfx-${{ env.JAVAFX_VERSION }}_osx-x64_bin-jmods.zip

          unzip javafx.zip

      - name: Create runtime
        run: |
          jlink \
          --module-path "$JAVA_HOME/jmods:javafx-jmods-${{ env.JAVAFX_VERSION }}" \
          --add-modules java.base,java.desktop,java.logging,java.net.http,java.xml,java.prefs,jdk.localedata,javafx.base,javafx.graphics,javafx.controls,javafx.fxml \
          --output runtime

      - name: Create DMG
        run: |
          jpackage \
          --name ${{ env.APP_NAME }} \
          --app-version ${{ env.APP_VERSION }} \
          --input target \
          --main-jar budget-${{ env.APP_VERSION }}.jar \
          --main-class ${{ env.MAIN_CLASS }} \
          --runtime-image runtime \
          --java-options "--enable-native-access=javafx.graphics" \
          --type dmg

      - name: Check generated DMG
        run: |
          ls -la
          find . -name "*.dmg"

      - name: Rename macOS installer
        run: |
          mv \
          Budget-${APP_VERSION}.dmg \
          budget_${APP_VERSION}_amd64.dmg

      - name: Upload macOS
        uses: actions/upload-artifact@v5
        with:
          name: macos-installer
          path: "*.dmg"



  release:
    name: Create GitHub Release
    needs:
      - build-windows
      - build-linux
      - build-macos

    runs-on: ubuntu-latest

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v5

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-installer/*.exe
            linux-installer/*.deb
            macos-installer/*.dmg