name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  APP_NAME: Budget
  MAIN_CLASS: com.nolabke.Main
  JAVA_VERSION: "25"
  JAVAFX_VERSION: "25.0.1"

jobs:

  build-windows:
    name: Windows installer
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Maven
        run: mvn clean package

      - name: Download JavaFX jmods
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://download2.gluonhq.com/openjfx/${{ env.JAVAFX_VERSION }}/openjfx-${{ env.JAVAFX_VERSION }}_windows-x64_bin-jmods.zip" `
            -OutFile javafx.zip

          Expand-Archive javafx.zip -DestinationPath .

      - name: Create runtime
        shell: powershell
        run: |

          jlink `
          --module-path "$env:JAVA_HOME\jmods;javafx-jmods-${{ env.JAVAFX_VERSION }}" `
          --add-modules java.base,java.desktop,javafx.controls,javafx.fxml `
          --output runtime

          dir runtime\bin

      - name: Create EXE
        shell: powershell
        run: |

          jpackage `
          --name $env:APP_NAME `
          --input target `
          --main-jar budget-1.0.0.jar `
          --main-class $env:MAIN_CLASS `
          --runtime-image runtime `
          --type exe `
          --win-menu `
          --win-shortcut

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: "*.exe"


  build-linux:
    name: Linux installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Maven
        run: mvn clean package

      - name: Create runtime
        run: |
          jlink \
          --module-path "$JAVA_HOME/jmods" \
          --add-modules java.base,java.desktop \
          --output runtime

      - name: Create DEB
        run: |
          jpackage \
          --name Budget \
          --input target \
          --main-jar budget-1.0.0.jar \
          --main-class com.nolabke.Main \
          --runtime-image runtime \
          --type deb

      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: "*.deb"



  build-macos:
    name: macOS installer
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Maven
        run: mvn clean package

      - name: Create runtime
        run: |
          jlink \
          --module-path "$JAVA_HOME/jmods" \
          --add-modules java.base,java.desktop \
          --output runtime

      - name: Create DMG
        run: |
          jpackage \
          --name Budget \
          --input target \
          --main-jar budget-1.0.0.jar \
          --main-class com.nolabke.Main \
          --runtime-image runtime \
          --type dmg

      - name: Upload macOS
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: "*.dmg"



  release:
    name: Create GitHub Release
    needs:
      - build-windows
      - build-linux
      - build-macos

    runs-on: ubuntu-latest

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-installer/*.exe
            linux-installer/*.deb
            macos-installer/*.dmg